add_newline = true
format = "$all"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_status]
conflicted = " conflict "
ahead = " ahead "
behind = " behind "
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = " modified "
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = " renamed "
deleted = " deleted "

[directory]
truncation_length = 100
truncate_to_repo=true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
disabled = true

[[battery.display]]
threshold = 50
style = "bold"

[git_commit]
disabled = false
commit_hash_length = 4

[git_state]
progress_divider = " of "

[line_break]
disabled = false

[memory_usage]
show_percentage = true
show_swap = false
threshold = -1
separator = "|"
style = "bold dimmed green"
disabled = true

[nodejs]
symbol = "ğŸ¤– "

[time]
disabled = false
utc_time_offset = -5

[username]
disabled = false
show_always = true


